export const faqData = [
  {
    id: 1,
    img: '/assets/faq/1.png',
    title: 'How does Foundation work for Users?',
    desc: 'Sign up to share your thoughts anonymously, guaranteeing utmost privacy. Unlock rewards by providing valuable insights, adding verification badges, and participating in posts. Customize your experience with our Filters & Preferences features, allowing you to tailor information and seek insights based on your preferences.',
  },
  {
    id: 2,
    img: '/assets/faq/1.png',
    title: 'How does Foundation work for businesses and researchers?',
    desc: 'We are working on advanced features that will provide valuable insights crucial for understanding trends of any kind. Based on advanced filtering, you will be able to reach out to and engage directly with these users as well.',
  },
  {
    id: 3,
    img: '/assets/faq/2.png',
    title: 'Can I earn money on Foundation?',
    desc: 'Earn FDX tokens for your participation. Soon, users will be able to withdraw these tokens to public exchanges, or trade them within our system.',
  },
  {
    id: 4,
    img: '/assets/faq/3.png',
    title: 'What are Verification Badges?',
    desc: 'Foundation counters misinformation with various verifications. Social media, email, and soon more options boost verification scores, building trust. Badges also give users the power to shape the filtering system. You will receive 0.96 FDX tokens for every badge added.',
  },
  {
    id: 5,
    img: '/assets/faq/4.png',
    title: 'How does the filtering and preferences system work?',
    desc: 'Our filtering system is constantly advancing and designed to give you full control over what you see in your feed. These settings are always remembered and can only be adjusted and reset by you.',
  },
  {
    id: 6,
    img: '/assets/faq/5.png',
    title: 'How do I create a post?',
    desc: 'Click "Create," select your post type, fill in the fields and submit it. It will immediately appear in everyone\'s feed. It costs 0.1 FDX to create a post.',
  },
  {
    id: 7,
    img: '/assets/faq/6.png',
    title: 'How do I participate in a post?',
    desc: 'Scroll through the main feed, select your option(s), and submit. You can also change your selection based on post settings and add your own options if allowed by the post creator. You are rewarded 0.96 FDX tokens for every post your participate in.',
  },
  {
    id: 8,
    img: '/assets/faq/7.png',
    title: 'How do I add an option to a Poll?',
    desc: 'If the post creator has enabled this setting, a plus sign on the post with "Add Option" will appear.',
  },
  {
    id: 9,
    img: '/assets/faq/8.png',
    title: 'How does Foundation ensure the accuracy of information shared?',
    desc: 'Foundation does not verify information; accuracy relies on user interactions and our objection and reporting systems.',
  },
  {
    id: 10,
    img: '/assets/faq/9.png',
    title: 'Can I control who sees my data and responses?',
    desc: 'All participation in posts on our system are fully anonymous.',
  },
  {
    id: 11,
    img: '/assets/faq/10.png',
    title: 'How do I object to an option in a post?',
    desc: 'If the post is Multiple Choice,Open Choice or Rank Choice, you can click the exclamation point next to the option. It costs 0.1 FDX to object to an option. If you remove the objection in the future, the same amount is returned to you.',
  },
  {
    id: 12,
    img: '/assets/faq/11.png',
    title: 'What would fail the Code of Conduct?',
    desc: 'Please see our Code of Conduct under Terms and Services for further information.',
  },
  {
    id: 13,
    img: '/assets/faq/12.png',
    title: 'Is there a mobile app for Foundation?',
    desc: 'Not yet.',
  },
];
