export const TopbarItems = [
  {
    id: 1,
    title: 'Profile',
    path: '/profile',
    signupPath: '/guest-signup',
    activePaths: [
      '/profile',
      '/profile/verification-badges',
      '/profile/post-activity',
      '/profile/feedback',
      '/profile/ledger',
      '/profile/hidden-posts',
      '/profile/shared-links',
      '/profile/user-settings',
      '/profile/lists',
    ],
    icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/topbar/profile.svg`,
    iconSelected: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/topbar/profile-filled.svg`,
    signupIcon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/topbar/signup.svg`,
  },
  {
    id: 2,
    title: 'Treasury',
    path: '/treasury',
    activePaths: [
      '/treasury',
      '/treasury/reward-schedule',
      '/treasury/buy-fdx',
      '/treasury/redemption-center',
      '/treasury/ledger',
    ],
    icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/svgs/treasury_logo_unselected.svg`,
    iconSelected: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/svgs/treasury_logo_selected.svg`,
  },
  // {
  //   id: 3,
  //   title: 'Lists',
  //   path: '/lists',
  //   activePaths: ['/lists'],
  //   icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/svgs/list.svg`,
  //   iconSelected: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/svgs/list_filled.svg`,
  // },
  // {
  //   id: 2,
  //   title: 'Chat',
  //   path: '/quest',
  //   activePaths: ['/quest'],
  //   icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/topbar/chat.svg`,
  // },
  {
    id: 4,
    title: 'Faqs',
    path: '/help/about',
    activePaths: ['/help/about', '/help/faq', '/help/terms-of-service', '/help/privacy-policy', '/help/contact-us'],
    icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/topbar/faq.svg`,
    iconSelected: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/topbar/faq-filled.svg`,
  },
];
