// export const TopbarItems = [
//   {
//     id: 1,
//     title: 'Home',
//     path: '/dashboard',
//     activePaths: ['/dashboard'],
//     icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/svgs/dashboard/home-white.svg`,
//   },
//   {
//     id: 2,
//     title: 'Create',
//     path: '/dashboard/quest',
//     activePaths: ['/dashboard/quest'],
//     icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/svgs/dashboard/create.svg`,
//   },
//   {
//     id: 3,
//     title: 'Profile',
//     path: '/dashboard/profile',
//     activePaths: [
//       '/dashboard/profile',
//       '/dashboard/profile/verification-badges',
//       '/dashboard/profile/ledger',
//       '/dashboard/profile/hidden-posts',
//       '/dashboard/profile/shared-links',
//       '/dashboard/profile/user-settings',
//     ],
//     icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/svgs/profile-logo.svg`,
//   },
//   {
//     id: 4,
//     title: 'Treasury',
//     path: '/dashboard/treasury',
//     activePaths: ['/dashboard/treasury', '/dashboard/treasury/ledger'],
//     icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/svgs/treasury/treasury-logo.svg`,
//   },
//   // {
//   //   id: 5,
//   //   title: 'Bookmarks',
//   //   path: '/dashboard/bookmark',
//   //   activePaths: ['/dashboard/bookmark'],
//   //   icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/bookmark/darkbookmark2.png`,
//   // },
// ];

export const TopbarItems = [
  {
    id: 1,
    title: 'Profile',
    path: '/dashboard/profile',
    signupPath: '/guest-signup',
    activePaths: [
      '/dashboard/profile',
      '/dashboard/profile/verification-badges',
      '/dashboard/profile/contributions',
      '/dashboard/profile/feedback',
      '/dashboard/profile/ledger',
      '/dashboard/profile/hidden-posts',
      '/dashboard/profile/shared-links',
      '/dashboard/profile/user-settings',
    ],
    icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/topbar/profile.svg`,
    iconSelected: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/topbar/profile-filled.svg`,
    signupIcon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/topbar/signup.svg`,
  },
  {
    id: 2,
    title: 'Treasury',
    path: '/dashboard/treasury',
    activePaths: ['/dashboard/treasury'],
    icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/svgs/treasury_logo_unselected.svg`,
    iconSelected: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/svgs/treasury_logo_selected.svg`,
  },
  {
    id: 2,
    title: 'Lists',
    path: '/dashboard/lists',
    activePaths: ['/dashboard/lists'],
    icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/svgs/list.svg`,
    iconSelected: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/svgs/list_filled.svg`,
  },
  // {
  //   id: 2,
  //   title: 'Chat',
  //   path: '/dashboard/quest',
  //   activePaths: ['/dashboard/quest'],
  //   icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/topbar/chat.svg`,
  // },
  {
    id: 4,
    title: 'Faqs',
    path: '/dashboard/help/about',
    activePaths: ['/dashboard/help/about', '/dashboard/help/faq', '/dashboard/help/contact-us'],
    icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/topbar/faq.svg`,
    iconSelected: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/topbar/faq-filled.svg`,
  },
];
