export const TopbarItems = [
  {
    id: 1,
    title: 'Profile',
    path: '/dashboard/profile',
    signupPath: '/guest-signup',
    activePaths: [
      '/dashboard/profile',
      '/dashboard/profile/verification-badges',
      '/dashboard/profile/post-activity',
      '/dashboard/profile/feedback',
      '/dashboard/profile/ledger',
      '/dashboard/profile/hidden-posts',
      '/dashboard/profile/shared-links',
      '/dashboard/profile/user-settings',
      '/dashboard/profile/lists',
    ],
    icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/topbar/profile.svg`,
    iconSelected: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/topbar/profile-filled.svg`,
    signupIcon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/topbar/signup.svg`,
  },
  {
    id: 2,
    title: 'Treasury',
    path: '/dashboard/treasury',
    activePaths: [
      '/dashboard/treasury',
      '/dashboard/treasury/reward-schedule',
      '/dashboard/treasury/buy-fdx',
      '/dashboard/treasury/redemption-center',
      '/dashboard/treasury/ledger',
    ],
    icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/svgs/treasury_logo_unselected.svg`,
    iconSelected: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/svgs/treasury_logo_selected.svg`,
  },
  // {
  //   id: 3,
  //   title: 'Lists',
  //   path: '/dashboard/lists',
  //   activePaths: ['/dashboard/lists'],
  //   icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/svgs/list.svg`,
  //   iconSelected: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/svgs/list_filled.svg`,
  // },
  // {
  //   id: 2,
  //   title: 'Chat',
  //   path: '/dashboard/quest',
  //   activePaths: ['/dashboard/quest'],
  //   icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/topbar/chat.svg`,
  // },
  {
    id: 4,
    title: 'Faqs',
    path: '/dashboard/help/about',
    activePaths: [
      '/help/about',
      '/help/faq',
      '/help/terms-of-service',
      '/help/privacy-policy',
      '/help/contact-us',
      '/dashboard/help/about',
      '/dashboard/help/faq',
      '/help/help/terms-of-service',
      '/help/help/privacy-policy',
      '/dashboard/help/contact-us',
    ],
    icon: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/topbar/faq.svg`,
    iconSelected: `${import.meta.env.VITE_S3_IMAGES_PATH}/assets/topbar/faq-filled.svg`,
  },
];
