# This is a basic workflow to help you get started with Actions
name: s3-depl
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ development ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called build
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      VITE_GG_APP_ID: ${{ vars.VITE_GG_APP_ID }}
      VITE_FB_APP_ID: ${{ vars.VITE_FB_APP_ID }}
      VITE_GOOGLE_RECAPTCH_SITE_KEY: ${{ vars.VITE_GOOGLE_RECAPTCH_SITE_KEY }}
      VITE_API_URL: ${{ vars.VITE_DEVELOPMENT_API_URL }}
      VITE_CLIENT_URL: ${{ vars.VITE_DEVELOPMENT_CLIENT_URL }}
      VITE_GITHUB_CLIENT_ID: ${{ vars.VITE_DEVELOPMENT_GITHUB_CLIENT_ID }}
      VITE_GITHUB_CLIENT_SECRET: ${{ vars.VITE_DEVELOPMENT_GITHUB_CLIENT_SECRET }}
      VITE_LINKEDIN_KEY: ${{ vars.VITE_LINKEDIN_KEY }}
      VITE_LINKEDIN_SECRET: ${{ vars.VITE_LINKEDIN_SECRET }}
      VITE_TWITTER_CONSUMER_KEY: ${{ vars.VITE_TWITTER_CONSUMER_KEY }}
      VITE_INSTAGRAM_CLIENT_ID: ${{ vars.VITE_INSTAGRAM_CLIENT_ID }}
      VITE_INSTAGRAM_CLIENT_SECRET: ${{ vars.VITE_INSTAGRAM_CLIENT_SECRET }}
      VITE_FIREBASE_API_KEY: ${{ vars.VITE_FIREBASE_API_KEY }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ vars.VITE_FIREBASE_AUTH_DOMAIN }}
      VITE_FIREBASE_PROJECT_ID: ${{ vars.VITE_FIREBASE_PROJECT_ID }}
      VITE_FIREBASE_STORAGE_BUCKET: ${{ vars.VITE_FIREBASE_STORAGE_BUCKET }}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ vars.VITE_FIREBASE_MESSAGING_SENDER_ID }}
      VITE_FIREBASE_APP_ID: ${{ vars.VITE_FIREBASE_APP_ID }}
      VITE_FIREBASE_MEASUREMENT_ID: ${{ vars.VITE_FIREBASE_MEASUREMENT_ID }}
    strategy:
      matrix:
        node-version: [20.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build React App
        run: npm install && npm run build
        env:
            CI: false
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./dist/ s3://development.on.foundation --delete && aws cloudfront create-invalidation --distribution-id "${{ secrets.DEVELOPMENT_DISTRIBUTION_ID }}" --paths "/*"
